services:
  - type: web
    name: social-content-generator-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://social-content-generator-backend.onrender.com 